Import-Module xDSCResourceDesigner
Test-xDscResource ..\DSCResources\MSFT_xADCommon
Test-xDscSchema ..\DSCResources\MSFT_xADCommon\MSFT_xADCommon.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADComputer
Test-xDscSchema ..\DSCResources\MSFT_xADComputer\MSFT_xADComputer.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADDomain
Test-xDscSchema ..\DSCResources\MSFT_xADDomain\MSFT_xADDomain.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADDomainController
Test-xDscSchema ..\DSCResources\MSFT_xADDomainController\MSFT_xADDomainController.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADDomainDefaultPasswordPolicy
Test-xDscSchema ..\DSCResources\MSFT_xADDomainDefaultPasswordPolicy\MSFT_xADDomainDefaultPasswordPolicy.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADDomainTrust
Test-xDscSchema ..\DSCResources\MSFT_xADDomainTrust\MSFT_xADDomainTrust.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADGroup
Test-xDscSchema ..\DSCResources\MSFT_xADGroup\MSFT_xADGroup.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADOrganizationalUnit
Test-xDscSchema ..\DSCResources\MSFT_xADOrganizationalUnit\MSFT_xADOrganizationalUnit.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADRecycleBin
Test-xDscSchema ..\DSCResources\MSFT_xADRecycleBin\MSFT_xADRecycleBin.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADSiteLink
Test-xDscSchema ..\DSCResources\MSFT_xADSiteLink\MSFT_xADSiteLink.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xADUser
Test-xDscSchema ..\DSCResources\MSFT_xADUser\MSFT_xADUser.schema.mof
Test-xDscResource ..\DSCResources\MSFT_xWaitForADDomain
Test-xDscSchema ..\DSCResources\MSFT_xWaitForADDomain\MSFT_xWaitForADDomain.schema.mof